# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [2]:
import numpy as np

In [5]:
Z = np.zeros(100)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


#### 2.Создать вектор размера 100, заполненный единицами

In [6]:
Z = np.ones(100)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


#### 3.Создать вектор размера 100, заполненный числом 3

In [7]:
Z = np.full(100, 3)
print(Z)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


#### 4. Поменять 2 строки в матрице

In [26]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 5. Создать вектор со значениями от 10 до 100

In [9]:
Z = np.arange(10,100)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


#### 6. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [11]:
Z = np.arange(16).reshape(4,4)
print(Z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 7. Создать 3x3 единичную матрицу

In [12]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 8. Создать массив 3x3x3 со случайными значениями

In [13]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.43524239 0.92443212 0.47838573]
  [0.49960059 0.07263059 0.3162588 ]
  [0.05313793 0.90414451 0.33692846]]

 [[0.83679412 0.72689232 0.46124068]
  [0.41759819 0.17736604 0.89310468]
  [0.91515833 0.97769574 0.06050505]]

 [[0.77949144 0.45149181 0.14562437]
  [0.62125172 0.48283144 0.97925014]
  [0.78228084 0.79743639 0.10887941]]]


#### 9. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [29]:
Z = np.random.random((10,10))
Z

array([[0.90975242, 0.18051221, 0.45963646, 0.8395529 , 0.29451649,
        0.58593327, 0.69276477, 0.73010672, 0.07153142, 0.48997792],
       [0.99847735, 0.58423358, 0.34839935, 0.75558826, 0.69078586,
        0.03616429, 0.62314548, 0.19291247, 0.66197804, 0.36079542],
       [0.10037525, 0.00413585, 0.59130908, 0.92500217, 0.34607413,
        0.18891104, 0.77413008, 0.89644486, 0.03933733, 0.57080802],
       [0.04749653, 0.17639621, 0.63305892, 0.16268896, 0.80650708,
        0.10308304, 0.68350869, 0.01389294, 0.49544932, 0.93128693],
       [0.56688289, 0.90801181, 0.07455951, 0.05189862, 0.99608568,
        0.17474185, 0.01249292, 0.28825348, 0.75753001, 0.53010938],
       [0.6864929 , 0.58014724, 0.49393141, 0.55589625, 0.1427932 ,
        0.22267562, 0.71429665, 0.48591817, 0.3084435 , 0.80732168],
       [0.39902006, 0.74717865, 0.181259  , 0.83375091, 0.49775798,
        0.9709161 , 0.02626334, 0.07213052, 0.92117938, 0.5205682 ],
       [0.94132708, 0.43148516, 0.9875744

In [30]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.00018444442484688572 0.9796021462733236


#### 10. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [15]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5184307334576022


#### 11. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [16]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 12. Перемножить матрицы 5x3 и 3x2

In [17]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 13. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [23]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 14. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [20]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 15. Отнять среднее из каждой строки в матрице

In [25]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.24983219  0.3506075   0.03497616  0.27894365 -0.077359   -0.32318236
   0.00988281 -0.28494079 -0.22850131  0.48940553]
 [-0.3071936  -0.09131842  0.12089581  0.13280291 -0.41185931 -0.35316126
  -0.04863013  0.23941696  0.44963025  0.26941677]
 [-0.00892153 -0.23480097 -0.04107022  0.13774998  0.33122244  0.2217017
   0.08422585  0.07139354 -0.08545364 -0.47604715]
 [-0.17392552  0.17526869  0.2689162  -0.05922628  0.30395912 -0.30073958
  -0.27500589 -0.40342139  0.23665915  0.2275155 ]
 [ 0.12409064  0.22282023 -0.39391934 -0.23652    -0.07182422 -0.44198414
   0.0075308  -0.02786261  0.4552679   0.36240074]]


In [22]:
Z = np.random.randint(0,10,(3,3))
n = 1  # Нумерация с нуля
print(Z)
print(Z[Z[:,n].argsort()])

[[6 0 2]
 [3 6 0]
 [1 2 5]]
[[6 0 2]
 [1 2 5]
 [3 6 0]]
